version: '3.5'
services:
  migration:
    build: .
    depends_on:
      - db
    #   - back
    command: >
      bash -c "./wait-for-it/wait-for-it.sh db:5432 -- npm run migration:run
      && npm run start:prod"
    environment:
      DB_HOST: postgres
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
